name: CI

on: [push]

jobs:

  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.9

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: cache poetry install
        uses: actions/cache@v2
        with:
          path: ~/.local
          key: poetry-1.8.3-0

      - uses: snok/install-poetry@v1
        with:
          version: 1.8.3
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: cache deps
        id: cache-deps
        uses: actions/cache@v2
        with:
          path: .venv
          key: pydeps-${{ hashFiles('**/poetry.lock') }}

      - run: poetry install --no-interaction --no-root
        if: steps.cache-deps.outputs.cache-hit != 'true'

      - run: poetry install --no-interaction

      - name: Code Quality
        run: poetry run black . --check

      - name: Test with pytest
        env:
          DJANGO_SETTINGS_MODULE: mywebsite.settings
          SECRETS_FILE: .confidential/ci.json
        run: poetry run pytest --cov . -n 2
